flowchart LR
    %% Database
    subgraph DB[Database]
        allowedUsers[(allowedUsers)]
        registeredUsers[(registeredUsers)]
        gaesteListe[(gaesteListe)]
    end

    %% Registration
    subgraph Registration
        subgraph Backend
            reg["register name + room_nr"]
            verify["verify_mail()"]
            regsave["save user to database"]
        end

        subgraph Frontend
            regUI["Registration UI"]
            codeUI["Bestätigungscode UI"]
        end
    end

    %% Login
    subgraph Login
        subgraph Backend
            login["login with name + room_nr"]
        end

        subgraph Frontend
            loginUI["Login UI"]
            personalUI["Personal Page"]
        end
    end

    %% Stueble Anmeldung
    subgraph Stueble
        subgraph Backend
            stubReg["stueble_register"]
            addGuest["add_guest"]
        end

        subgraph Frontend
            stubUI["Zu Stueble anmelden"]
            inviteUI["Gast einladen"]
        end
    end

    %% Host hinzufügen
    subgraph Host
        subgraph Backend
            addHost["addHost (nur für Tutoren)"]
            checkPerms["check_relos()"]
        end

        subgraph Frontend
            addHostUI["Stueble-Host hinzufügen"]
            hostAddedUI["Host hinzugefügt"]
        end
    end

    %% Connections
    allowedUsers --> reg
    reg --> verify --> regsave
    regUI --> reg
    codeUI --> verify
    regsave --> registeredUsers

    registeredUsers --> login
    login --> loginUI
    login --> personalUI

    stubReg --> addGuest --> gaesteListe
    stubUI --> stubReg
    inviteUI --> addGuest

    addHost --> checkPerms
    addHost --> hostAddedUI
    checkPerms --> addHostUI
